server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:file:~/build/data/petstoredb
    username: sa
    password:
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true