server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost/petstoredb
    username:
    password:

  jackson:
    serialization:
      indent_output: true

  jpa:
    hibernate:
      ddl-auto: create